### ISSUE TITLE
`cookies: VueUniversalCookies.Options` hasn't set.

### ISSUE THREAD

**Issue by Temarie** [S64/vue-universal-cookies#1]
Hi! I am trying to implement nuxt-universal-cookies and getting this error with latest nuxt. How can I fix this?

**Comment by fbrbovic** [comment]
same problem

**Comment by S64** [comment]
@Temarie @fbrbovic 

Hello. Thanks for trying to use `nuxt-universal-cookies` 😊 ! 

Sorry, Couldn't reproduce it. This error is thrown on run w/ invalid configuration. (normally)
If you have some time, Please try this steps:

- I've released new version `v0.0.5`. It contains `nuxt#1.0.0` support.
- Have you successfully to test [packages/example-nuxt](https://github.com/S64/vue-universal-cookies/tree/master/packages/example-nuxt)?
- Your [nuxt.config.js](https://github.com/S64/vue-universal-cookies/blob/master/packages/example-nuxt/nuxt.config.js) is correct? Please check diff.

**Comment by Temarie** [comment]
> Have you successfully to test packages/example-nuxt?
 - successfull

I update to version v0.0.5, but the error still repeats

This modules section in my nuxt config:

![619a31c944817b63819d3581567b2cd2 1](https://user-images.githubusercontent.com/931745/35211148-0ca3cac0-ff77-11e7-97ff-7bb8268d95de.png)

**Comment by Emericanec** [comment]
same problem

**Comment by Emericanec** [comment]
<img width="653" alt="screen shot 2018-01-29 at 18 57 33" src="https://user-images.githubusercontent.com/7316100/35516869-4e10b27a-0526-11e8-85fe-8a64c3816967.png">
my nuxt.config.js

**Comment by Emericanec** [comment]
same problem. my nuxt.config.js :
<img width="653" alt="screen shot 2018-01-29 at 18 57 33" src="https://user-images.githubusercontent.com/7316100/35516963-93d734c8-0526-11e8-8e80-93882baaea29.png">

**Comment by stephenrichard** [comment]
Hey,

Thanks for the plugin, it seems to be exactly what I need. But I also got the same error 
`[Vue warn]: Error in beforeCreate hook: "Error: cookies: VueUniversalCookies.Options hasn't set."`
![capture d ecran 2018-01-30 a 21 56 23](https://user-images.githubusercontent.com/4067686/35590884-76bd8058-0608-11e8-9ee6-bb60419c794d.png)
Any progress on the issue ?

**Comment by benfavre** [comment]
I get this in dev mode and I see this on screen load number 2.
I have my npm command set as : "backpack dev"

**Comment by justin-schroeder** [comment]
FWIW I get the same error, Nuxt 1.0.0.

**Comment by elpete** [comment]
From what I can tell, this only happens on the second request to the server.  The initial request is successful.  Running Nuxt 1.3.0 and nuxt-universal-cookies 0.0.5.

**Comment by nurdism** [comment]
+1 same issue, The initial request is successful, 2nd+ request errors.

**Comment by vacijj** [comment]
Hi,

the package is exactly what I was looking for. 

I get the same error as described above. I am running nuxt 1.3.0 and nuxt-universal-cookies 0.0.5

**Comment by ghost** [comment]
+1 same issue

**Comment by frankier** [comment]
I had the same problem. I switched to https://github.com/microcipcip/cookie-universal which seems to work just fine.

**Comment by mtskf** [comment]
Same issue here...

**Comment by chanlito** [comment]
Same issue here 👋

**Comment by homerjam** [comment]
+1

**Comment by xinbenlv** [comment]
Same issue here
